"""creation schema initial

Revision ID: deedc3b93eb7
Revises: 
Create Date: 2026-07-21 14:48:48.974934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'deedc3b93eb7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('organization_type', sa.String(length=30), nullable=False),
    sa.Column('website', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=True)
    op.create_index(op.f('ix_organizations_organization_type'), 'organizations', ['organization_type'], unique=False)
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('base_url', sa.Text(), nullable=True),
    sa.Column('reliability_weight', sa.Float(), server_default=sa.text('1.0'), nullable=False),
    sa.Column('configuration', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sources_name'), 'sources', ['name'], unique=True)
    op.create_index(op.f('ix_sources_source_type'), 'sources', ['source_type'], unique=False)
    op.create_table('topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_topics_slug'), 'topics', ['slug'], unique=True)
    op.create_table('business_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('metric_code', sa.String(length=100), nullable=False),
    sa.Column('metric_name', sa.String(length=200), nullable=False),
    sa.Column('numeric_value', sa.Float(), nullable=True),
    sa.Column('text_value', sa.Text(), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('source_system', sa.String(length=150), nullable=False),
    sa.Column('source_reference', sa.Text(), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_validated', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('validated_by', sa.String(length=200), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_metrics_metric_code'), 'business_metrics', ['metric_code'], unique=False)
    op.create_index(op.f('ix_business_metrics_organization_id'), 'business_metrics', ['organization_id'], unique=False)
    op.create_index(op.f('ix_business_metrics_period_end'), 'business_metrics', ['period_end'], unique=False)
    op.create_index(op.f('ix_business_metrics_period_start'), 'business_metrics', ['period_start'], unique=False)
    op.create_index(op.f('ix_business_metrics_source_system'), 'business_metrics', ['source_system'], unique=False)
    op.create_table('organization_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(length=200), nullable=False),
    sa.Column('normalized_alias', sa.String(length=200), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'normalized_alias', name='uq_organization_normalized_alias')
    )
    op.create_index(op.f('ix_organization_aliases_normalized_alias'), 'organization_aliases', ['normalized_alias'], unique=False)
    op.create_index(op.f('ix_organization_aliases_organization_id'), 'organization_aliases', ['organization_id'], unique=False)
    op.create_table('watch_queries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('category', sa.String(length=50), server_default='organization', nullable=False),
    sa.Column('frequency', sa.String(length=30), server_default='daily', nullable=False),
    sa.Column('filters', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watch_queries_category'), 'watch_queries', ['category'], unique=False)
    op.create_index(op.f('ix_watch_queries_organization_id'), 'watch_queries', ['organization_id'], unique=False)
    op.create_table('pipeline_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_type', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('watch_query_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), server_default='running', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('items_received', sa.Integer(), server_default='0', nullable=False),
    sa.Column('items_created', sa.Integer(), server_default='0', nullable=False),
    sa.Column('items_duplicated', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('statistics', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['watch_query_id'], ['watch_queries.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mentions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('pipeline_run_id', sa.Integer(), nullable=True),
    sa.Column('external_id', sa.String(length=300), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('title', sa.String(length=1000), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('clean_text', sa.Text(), nullable=True),
    sa.Column('author_name', sa.String(length=300), nullable=True),
    sa.Column('author_handle', sa.String(length=300), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('detected_language', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=150), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('engagement', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('processing_status', sa.String(length=30), server_default='new', nullable=False),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_hash'),
    sa.UniqueConstraint('source_id', 'external_id', name='uq_mention_source_external_id')
    )
    op.create_table('reputation_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('pipeline_run_id', sa.Integer(), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('period_type', sa.String(length=20), server_default='weekly', nullable=False),
    sa.Column('reputation_score', sa.Float(), nullable=False),
    sa.Column('mention_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('positive_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('neutral_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('negative_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('positive_rate', sa.Float(), nullable=True),
    sa.Column('negative_rate', sa.Float(), nullable=True),
    sa.Column('delta_previous_period', sa.Float(), nullable=True),
    sa.Column('dominant_topic_id', sa.Integer(), nullable=True),
    sa.Column('analyst_summary', sa.Text(), nullable=True),
    sa.Column('formula_version', sa.String(length=50), server_default='v1', nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.ForeignKeyConstraint(['dominant_topic_id'], ['topics.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'period_start', 'period_end', 'formula_version', name='uq_reputation_snapshot_period')
    )
    op.create_index(op.f('ix_reputation_snapshots_dominant_topic_id'), 'reputation_snapshots', ['dominant_topic_id'], unique=False)
    op.create_index(op.f('ix_reputation_snapshots_organization_id'), 'reputation_snapshots', ['organization_id'], unique=False)
    op.create_index(op.f('ix_reputation_snapshots_period_end'), 'reputation_snapshots', ['period_end'], unique=False)
    op.create_index(op.f('ix_reputation_snapshots_period_start'), 'reputation_snapshots', ['period_start'], unique=False)
    op.create_index(op.f('ix_reputation_snapshots_pipeline_run_id'), 'reputation_snapshots', ['pipeline_run_id'], unique=False)
    op.create_table('strategic_angles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('pipeline_run_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('priority_score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=30), server_default='proposed', nullable=False),
    sa.Column('target_platforms', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('model_provider', sa.String(length=100), nullable=True),
    sa.Column('model_name', sa.String(length=200), nullable=True),
    sa.Column('model_version', sa.String(length=100), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategic_angles_organization_id'), 'strategic_angles', ['organization_id'], unique=False)
    op.create_index(op.f('ix_strategic_angles_pipeline_run_id'), 'strategic_angles', ['pipeline_run_id'], unique=False)
    op.create_index(op.f('ix_strategic_angles_status'), 'strategic_angles', ['status'], unique=False)
    op.create_table('generated_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('strategic_angle_id', sa.Integer(), nullable=True),
    sa.Column('pipeline_run_id', sa.Integer(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('platform', sa.String(length=30), nullable=False),
    sa.Column('content_by_language', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('image_prompt', sa.Text(), nullable=True),
    sa.Column('tone', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('status', sa.String(length=30), server_default='draft', nullable=False),
    sa.Column('model_provider', sa.String(length=100), nullable=True),
    sa.Column('model_name', sa.String(length=200), nullable=True),
    sa.Column('model_version', sa.String(length=100), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by', sa.String(length=200), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by', sa.String(length=200), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('external_publication_id', sa.String(length=300), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['strategic_angle_id'], ['strategic_angles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_posts_organization_id'), 'generated_posts', ['organization_id'], unique=False)
    op.create_index(op.f('ix_generated_posts_pipeline_run_id'), 'generated_posts', ['pipeline_run_id'], unique=False)
    op.create_index(op.f('ix_generated_posts_platform'), 'generated_posts', ['platform'], unique=False)
    op.create_index(op.f('ix_generated_posts_status'), 'generated_posts', ['status'], unique=False)
    op.create_index(op.f('ix_generated_posts_strategic_angle_id'), 'generated_posts', ['strategic_angle_id'], unique=False)
    op.create_table('mention_organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mention_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('detection_method', sa.String(length=30), server_default='alias_matching', nullable=False),
    sa.ForeignKeyConstraint(['mention_id'], ['mentions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mention_id', 'organization_id', name='uq_mention_organization')
    )
    op.create_table('mention_topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mention_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('detection_method', sa.String(length=50), server_default='llm', nullable=False),
    sa.ForeignKeyConstraint(['mention_id'], ['mentions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mention_id', 'topic_id', name='uq_mention_topic')
    )
    op.create_index(op.f('ix_mention_topics_mention_id'), 'mention_topics', ['mention_id'], unique=False)
    op.create_index(op.f('ix_mention_topics_topic_id'), 'mention_topics', ['topic_id'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mention_organization_id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), server_default='medium', nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), server_default='open', nullable=False),
    sa.Column('assigned_to', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.ForeignKeyConstraint(['mention_organization_id'], ['mention_organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_alert_type'), 'alerts', ['alert_type'], unique=False)
    op.create_index(op.f('ix_alerts_mention_organization_id'), 'alerts', ['mention_organization_id'], unique=False)
    op.create_index(op.f('ix_alerts_severity'), 'alerts', ['severity'], unique=False)
    op.create_index(op.f('ix_alerts_status'), 'alerts', ['status'], unique=False)
    op.create_table('mention_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mention_organization_id', sa.Integer(), nullable=False),
    sa.Column('model_provider', sa.String(length=100), nullable=True),
    sa.Column('model_name', sa.String(length=200), nullable=False),
    sa.Column('model_version', sa.String(length=100), nullable=True),
    sa.Column('sentiment_label', sa.String(length=20), nullable=False),
    sa.Column('positive_score', sa.Float(), nullable=True),
    sa.Column('neutral_score', sa.Float(), nullable=True),
    sa.Column('negative_score', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('analysis_language', sa.String(length=20), nullable=True),
    sa.Column('is_current', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.ForeignKeyConstraint(['mention_organization_id'], ['mention_organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mention_analyses_mention_organization_id'), 'mention_analyses', ['mention_organization_id'], unique=False)
    op.create_index(op.f('ix_mention_analyses_sentiment_label'), 'mention_analyses', ['sentiment_label'], unique=False)
    op.create_table('post_evidence_mentions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('generated_post_id', sa.Integer(), nullable=False),
    sa.Column('mention_id', sa.Integer(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('evidence_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['generated_post_id'], ['generated_posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mention_id'], ['mentions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('generated_post_id', 'mention_id', name='uq_post_evidence_mention')
    )
    op.create_index(op.f('ix_post_evidence_mentions_generated_post_id'), 'post_evidence_mentions', ['generated_post_id'], unique=False)
    op.create_index(op.f('ix_post_evidence_mentions_mention_id'), 'post_evidence_mentions', ['mention_id'], unique=False)
    op.create_table('post_evidence_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('generated_post_id', sa.Integer(), nullable=False),
    sa.Column('business_metric_id', sa.Integer(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('evidence_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_metric_id'], ['business_metrics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['generated_post_id'], ['generated_posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('generated_post_id', 'business_metric_id', name='uq_post_evidence_metric')
    )
    op.create_index(op.f('ix_post_evidence_metrics_business_metric_id'), 'post_evidence_metrics', ['business_metric_id'], unique=False)
    op.create_index(op.f('ix_post_evidence_metrics_generated_post_id'), 'post_evidence_metrics', ['generated_post_id'], unique=False)
    op.create_table('response_drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('pipeline_run_id', sa.Integer(), nullable=True),
    sa.Column('content_by_language', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tone', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('status', sa.String(length=30), server_default='draft', nullable=False),
    sa.Column('model_provider', sa.String(length=100), nullable=True),
    sa.Column('model_name', sa.String(length=200), nullable=True),
    sa.Column('model_version', sa.String(length=100), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('external_response_id', sa.String(length=300), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_response_drafts_alert_id'), 'response_drafts', ['alert_id'], unique=False)
    op.create_index(op.f('ix_response_drafts_pipeline_run_id'), 'response_drafts', ['pipeline_run_id'], unique=False)
    op.create_index(op.f('ix_response_drafts_status'), 'response_drafts', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_response_drafts_status'), table_name='response_drafts')
    op.drop_index(op.f('ix_response_drafts_pipeline_run_id'), table_name='response_drafts')
    op.drop_index(op.f('ix_response_drafts_alert_id'), table_name='response_drafts')
    op.drop_table('response_drafts')
    op.drop_index(op.f('ix_post_evidence_metrics_generated_post_id'), table_name='post_evidence_metrics')
    op.drop_index(op.f('ix_post_evidence_metrics_business_metric_id'), table_name='post_evidence_metrics')
    op.drop_table('post_evidence_metrics')
    op.drop_index(op.f('ix_post_evidence_mentions_mention_id'), table_name='post_evidence_mentions')
    op.drop_index(op.f('ix_post_evidence_mentions_generated_post_id'), table_name='post_evidence_mentions')
    op.drop_table('post_evidence_mentions')
    op.drop_index(op.f('ix_mention_analyses_sentiment_label'), table_name='mention_analyses')
    op.drop_index(op.f('ix_mention_analyses_mention_organization_id'), table_name='mention_analyses')
    op.drop_table('mention_analyses')
    op.drop_index(op.f('ix_alerts_status'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_severity'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_mention_organization_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_alert_type'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_mention_topics_topic_id'), table_name='mention_topics')
    op.drop_index(op.f('ix_mention_topics_mention_id'), table_name='mention_topics')
    op.drop_table('mention_topics')
    op.drop_table('mention_organizations')
    op.drop_index(op.f('ix_generated_posts_strategic_angle_id'), table_name='generated_posts')
    op.drop_index(op.f('ix_generated_posts_status'), table_name='generated_posts')
    op.drop_index(op.f('ix_generated_posts_platform'), table_name='generated_posts')
    op.drop_index(op.f('ix_generated_posts_pipeline_run_id'), table_name='generated_posts')
    op.drop_index(op.f('ix_generated_posts_organization_id'), table_name='generated_posts')
    op.drop_table('generated_posts')
    op.drop_index(op.f('ix_strategic_angles_status'), table_name='strategic_angles')
    op.drop_index(op.f('ix_strategic_angles_pipeline_run_id'), table_name='strategic_angles')
    op.drop_index(op.f('ix_strategic_angles_organization_id'), table_name='strategic_angles')
    op.drop_table('strategic_angles')
    op.drop_index(op.f('ix_reputation_snapshots_pipeline_run_id'), table_name='reputation_snapshots')
    op.drop_index(op.f('ix_reputation_snapshots_period_start'), table_name='reputation_snapshots')
    op.drop_index(op.f('ix_reputation_snapshots_period_end'), table_name='reputation_snapshots')
    op.drop_index(op.f('ix_reputation_snapshots_organization_id'), table_name='reputation_snapshots')
    op.drop_index(op.f('ix_reputation_snapshots_dominant_topic_id'), table_name='reputation_snapshots')
    op.drop_table('reputation_snapshots')
    op.drop_table('mentions')
    op.drop_table('pipeline_runs')
    op.drop_index(op.f('ix_watch_queries_organization_id'), table_name='watch_queries')
    op.drop_index(op.f('ix_watch_queries_category'), table_name='watch_queries')
    op.drop_table('watch_queries')
    op.drop_index(op.f('ix_organization_aliases_organization_id'), table_name='organization_aliases')
    op.drop_index(op.f('ix_organization_aliases_normalized_alias'), table_name='organization_aliases')
    op.drop_table('organization_aliases')
    op.drop_index(op.f('ix_business_metrics_source_system'), table_name='business_metrics')
    op.drop_index(op.f('ix_business_metrics_period_start'), table_name='business_metrics')
    op.drop_index(op.f('ix_business_metrics_period_end'), table_name='business_metrics')
    op.drop_index(op.f('ix_business_metrics_organization_id'), table_name='business_metrics')
    op.drop_index(op.f('ix_business_metrics_metric_code'), table_name='business_metrics')
    op.drop_table('business_metrics')
    op.drop_index(op.f('ix_topics_slug'), table_name='topics')
    op.drop_table('topics')
    op.drop_index(op.f('ix_sources_source_type'), table_name='sources')
    op.drop_index(op.f('ix_sources_name'), table_name='sources')
    op.drop_table('sources')
    op.drop_index(op.f('ix_organizations_organization_type'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
